import { useState } from "react";

const UserList = () => {
  /*
    formData = temporary form state

    This only stores what user types in the input fields.
    We removed "id" from formData because user should not manually enter ID.
    ID should be generated by our app.
  */
  const [formData, setFormData] = useState({
    name: "",
    role: "",
  });

  /*
    Users = actual saved data

    This is the real list that gets rendered on screen.
    Each user must have a unique id because React uses it as key.
  */
  const [users, setUsers] = useState([
    { id: 1, name: "Nirmal", role: "Frontend" },
    { id: 2, name: "Rahul", role: "Backend" },
    { id: 3, name: "Priya", role: "UI Designer" },
    { id: 4, name: "Amit", role: "QA Engineer" },
  ]);

  /*
    editingId tells us current mode.

    null = Add mode
    number = Edit mode

    Example:
    editingId = null  → form will add new user
    editingId = 2     → form will update user with id 2
  */
  const [editingId, setEditingId] = useState(null);

  const handleChange = (e) => {
    const name = e.target.name;
    const value = e.target.value;

    /*
      Controlled input concept:

      Input value comes from React state.
      onChange updates React state.

      [name]: value means dynamic update.

      Example:
      If input has name="role",
      then this becomes:
      role: value
    */
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    /*
      Basic validation:

      If name or role is empty, stop the function.
    */
    if (!formData.name || !formData.role) {
      return;
    }

    /*
      If editingId is not null, we are editing existing user.

      We use map because:
      - array length stays same
      - only one user changes
      - others remain same

      Example:
      [Nirmal, Rahul, Priya]
      Edit Rahul
      Result:
      [Nirmal, Updated Rahul, Priya]
    */
    if (editingId !== null) {
      setUsers((prev) =>
        prev.map((user) => {
          if (user.id === editingId) {
            return {
              ...user, // keeps existing properties like id
              name: formData.name,
              role: formData.role,
            };
          }

          return user; // unchanged users
        })
      );
    } else {
      /*
        Add mode:

        ID is generated automatically.

        If Users array is empty:
        new id = 1

        Otherwise:
        new id = highest existing id + 1

        Example:
        existing ids = [1, 2, 4]
        highest id = 4
        new id = 5
      */
      const newUser = {
        id:
          users.length === 0
            ? 1
            : Math.max(...users.map((user) => user.id)) + 1,
        name: formData.name,
        role: formData.role,
      };

      /*
        Add new user immutably.

        prev = old users array
        [...prev, newUser] = new array with old users + new user
      */
      setUsers((prev) => [...prev, newUser]);
    }

    /*
      After add/update:
      - clear form
      - return to add mode
    */
    setFormData({
      name: "",
      role: "",
    });

    setEditingId(null);
  };

  /*
    Remove user:

    filter creates a new array.

    Keep only users whose id does not match clicked id.

    Example:
    clicked id = 2
    user.id !== 2
    Rahul gets removed, others stay.
  */
  const removeHandler = (id) => {
    setUsers((prev) => prev.filter((user) => user.id !== id));
  };

  /*
    Edit user:

    When edit button is clicked:
    - fill form with selected user's data
    - store selected user's id in editingId
    - submit button changes to "Update User"
  */
  const editHandler = (user) => {
    setFormData({
      name: user.name,
      role: user.role,
    });

    setEditingId(user.id);
  };

  return (
    <>
      <div>UserList</div>

      {users.map((user) => (
        <div key={user.id}>
          <div>{user.id}</div>
          <p>{user.name}</p>
          <p>{user.role}</p>

          <button
            className="bg-red-700 p-3"
            onClick={() => removeHandler(user.id)}
          >
            Remove
          </button>

          <button
            className="bg-yellow-400 p-3"
            onClick={() => editHandler(user)}
          >
            Edit User
          </button>
        </div>
      ))}

      <br />

      <div>{editingId !== null ? "EDIT User" : "ADD User"}</div>

      <form onSubmit={handleSubmit}>
        Name:
        <input
          type="text"
          name="name"
          value={formData.name}
          onChange={handleChange}
        />

        <br />

        Role:
        <input
          type="text"
          name="role"
          value={formData.role}
          onChange={handleChange}
        />

        <br />

        <button type="submit" className="p-3 bg-green-700">
          {editingId !== null ? "Update User" : "Add User Now"}
        </button>
      </form>
    </>
  );
};

export default UserList;
